### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by anup-das** [vbaderks/WICExplorer#2]
Cannot compile the code with Microsoft Visual Studio Community 2022 Version 17.5.3

See the build output (attached)
[Build output.txt](https://github.com/vbaderks/WICExplorer/files/11141951/Build.output.txt)

**Comment by vbaderks** [comment]
Header units are broken in VS 17.5:
https://developercommunity.visualstudio.com/t/Header-unit-does-not-recognize-__try/10232019
(you can vote it up)

Problem was already report to Microsoft in december 2022. 

As a workaround, it is possible to also install the 17.4 C++ compiler in VS 17.5.3 and use that one.
Problem still persists in latest VS 17.6 Preview 2.0 version.

**Comment by vbaderks** [comment]
@anup-das : FYI: I have updated Directory.Build.Props to explicit require that the 14.34.31933 toolset is used.
